name: CI/CD for Electron App

on:
  create:
    ref_type: branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  test:
    # Call reusable test workflow
    uses: Vicky-ux1820/pipeline-practice/github/workflows/test-workflow.yml@main
    with:
      node-version: "16"

  build:
    needs: test  # This ensures the test job must pass before build runs
    uses: Vicky-ux1820/pipeline-practice/github/workflows/build-workflow.yml@main
    with:
      node-version: "16"

  deploy:
    needs: build
    uses: Vicky-ux1820/pipeline-practice/github/workflows/deploy-workflow.yml@main
    with:
      tag: v${{ github.run_number }}
