name: CI/CD for Electron App

on:
  create:
    ref_type: branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  test:
    # Call reusable test workflow
    uses: Vicky-ux1820/pipeline-practice/.github/workflows/test-workflow.yml@main
    with:
      node-version: "16"

  build:
    uses: ./.github/workflows/build-workflow.yml
    with:
      node-version: "16"

  deploy:
    needs: build
    uses: ./.github/workflows/deploy-workflow.yml
    with:
      tag: v${{ github.run_number }}
